### ISSUE TITLE
v3: TypeScriptHelpers is not a function

### ISSUE THREAD

**Issue by xaviergonz** [fuse-box/fuse-box#1011]
when updating to v3 require("fuse-box").TypeScriptHelpers is not a function anymore and therefore cannot be used as a plugin. This was ok on v2.

**Comment by nchanged** [comment]
@xaviergonz that's right it has been removed,  please use `tslib` instead 
https://github.com/Microsoft/tslib

**Comment by xaviergonz** [comment]
Ah, shouldn't the docs be updated then?

**Comment by xaviergonz** [comment]
https://fuse-box.org/page/typescript-helpers-plugin#extended-metadata-properties

**Comment by nchanged** [comment]
Sorry about that, it should have been removed
