### ISSUE TITLE
Separate bundle for vendor

### ISSUE THREAD

**Issue by davidanaya** [fuse-box/fuse-box#631]
Hi, I'm trying to configure my Angular project to have 3 different bundles, one for polyfills, one for vendors (Angular libraries, rxjs) and one for just my project files.

In webpack I use this
```
'polyfills': './src/polyfills.ts',
'vendor': './src/vendor.ts',
'app': './src/main.ts'
```
where my main.ts is the entrance point of my Angular app, polyfills is this
```
import 'core-js/es6';
import 'core-js/es7/reflect';
require('zone.js/dist/zone');

if (process.env.ENV === 'production') {
  // Production
} else {
  // Development and test
  Error['stackTraceLimit'] = Infinity;
  require('zone.js/dist/long-stack-trace-zone');
}
```
and vendor.ts
```
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/compiler';
import '@angular/http';
import '@angular/router';
import '@angular/forms';

import 'rxjs';
import './rxjs-extensions';
```
In rxjs.extensions.ts I define the imports for the operators I use with my observables
```
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';
```
This works in webpack, and gives me a 2.4MB for vendor.js, 500K for polyfill.js and other 500-ish for my app.js

In fusebox I tried with this
```
fuse.bundle('polyfills').instructions('> polyfills.ts');
fuse.bundle('vendor').instructions('> vendor.ts');
fuse.bundle('app').instructions('> main.ts').watch().hmr();
```
and it seems to work fine, the bundles are created and the app.js is also smaller than the one with webpack, but then when I load the app I get an error ```ERROR TypeError: this.http.get(...).map is not a function``` and ```GET http://localhost:4444/rxjs/Rx 404 (Not Found)```

I check the vendor.js and I think the library is inside.
Any idea what I'm doing wrong?
Thanks!

**Comment by nchanged** [comment]
Hi
* Use [WebIndexPlugin](http://fuse-box.org/plugins/webindexplugin#webindexplugin)
It makes sure of the bundle order (vendor.js) should come first

* Vendors are created differently
http://fuse-box.org/page/bundle#creating-vendors

```
instructions(`~ main.ts`)
```

* Modify your application instruction to avoid vendors in the bundle

```
instructions(`> [main.ts]`)
```

Use `2.2.0-beta.16` it will spit warning if you have libraries in use which use `browser` field.


Try [this](https://github.com/fuse-box/fuse-box-examples/tree/master/examples/vendor-splitting) example it does exactly what is described above. And as always, read up on [docs](fuse-box.org)

Cheers

**Comment by davidanaya** [comment]
Sorry, I copied the wrong config for my fuse, I was actually using this:
```
fuse.bundle('polyfills').instructions('> polyfills.ts');
fuse.bundle('vendor').instructions('~ main.ts vendor.ts');
fuse.bundle('app').instructions('!> [main.ts]').watch().hmr();
```
I included vendor.ts in the second bundle just to make sure my rxjs was included, but it doesn´t make a difference to do it or not, same error displayed in either case.

I was already using WebIndexPlugin, and the order in my index.html seems fine, the same I have defined.

I updated to ```2.2.0-beta.16``` and now I have some other errors that I didn´t have before and also a warning about the ``browser``` field. Not a clue what that is about, so I'll try to find out and fix it.

**Comment by nchanged** [comment]
it @davidanaya it says add target("browser") or target : browser to the config.
http://fuse-box.org/page/configuration#target

**Comment by nchanged** [comment]
And always clear the cache if you change `fuse.js`

**Comment by nchanged** [comment]
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.
